import { getOptionsForVote } from '@/utils/getRandomPokemon';
import { useEffect, useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  const [data, setData] = useState({ firstId: 0, secondId: 0});

  useEffect(() => {
    const data = getOptionsForVote();
    setData({ firstId: data.firstId!, secondId: data.secondId! });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-400 flex flex-col w-full h-screen justify-center items-center'>
        <div className='max-w-lg'>
          <div className='text-2xl text-center mb-16'>Which Pokémon is Rounder?</div>
          <div className='border rounded-lg p-8 flex justify-between items-center'>
            <div className='w-16 h-16 bg-red-200'>{data.firstId}</div>
            <div className='text-2xl'>Vs</div>
            <div className='w-16 h-16 bg-red-200'>{data.secondId}</div>
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
