import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-400 flex w-full h-screen justify-center items-center'>
        <div className='text-3xl font-bold underline text-red-500'>Hola mundo</div>
      </main>
    </>
  )
}

export default Home
