import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-400 flex flex-col w-full h-screen justify-center items-center'>
        <div className='max-w-lg'>
          <div className='text-2xl text-center mb-16'>Which Pokémon is Rounder?</div>
          <div className='border rounded-lg p-8 flex justify-between items-center'>
            <div className='w-16 h-16 bg-red-200'/>
            <div className='text-2xl'>Vs</div>
            <div className='w-16 h-16 bg-red-200'/>
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
